// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartIndustries.Smartlock.Platform.Shared.Infrastructure.Persistence.EntityFramerWorkCore.Configuration;

#nullable disable

namespace SmartIndustries.Smartlock.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260615171300_AddRoles")]
    partial class AddRoles
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.Administration.Domain.Model.Aggregates.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("Deletable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("deletable");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_roles");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.SpaceManagement.Domain.Model.Aggregates.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_organizations");

                    b.ToTable("organizations");
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.Administration.Domain.Model.Aggregates.Role", b =>
                {
                    b.OwnsOne("SmartIndustries.Smartlock.Platform.Shared.Domain.Model.ValueObjects.GenericName", "Name", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("name");

                            b1.HasKey("Id")
                                .HasName("p_k_roles");

                            b1.ToTable("roles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_roles_roles_id");
                        });

                    b.OwnsOne("SmartIndustries.Smartlock.Platform.Administration.Domain.Model.ValueObjects.RolePermissions", "Permissions", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<bool>("CanConnectDevices")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("can_connect_devices");

                            b1.Property<bool>("CanCreatePeople")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("can_create_people");

                            b1.Property<bool>("CanCreateSites")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("can_create_sites");

                            b1.HasKey("Id")
                                .HasName("p_k_roles");

                            b1.ToTable("roles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_roles_roles_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Permissions")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.OwnsOne("SmartIndustries.Smartlock.Platform.Shared.Domain.Model.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("varchar(255)")
                                .HasColumnName("email");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("i_x_users_email");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.OwnsOne("SmartIndustries.Smartlock.Platform.Shared.Domain.Model.ValueObjects.FullName", "Name", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("last_name");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.SpaceManagement.Domain.Model.Aggregates.Organization", b =>
                {
                    b.OwnsOne("SmartIndustries.Smartlock.Platform.Shared.Domain.Model.ValueObjects.GenericName", "Name", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("name");

                            b1.HasKey("Id")
                                .HasName("p_k_organizations");

                            b1.ToTable("organizations");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_organizations_organizations_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
