// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartIndustries.Smartlock.Platform.Shared.Infrastructure.Persistence.EntityFramerWorkCore.Configuration;

#nullable disable

namespace SmartIndustries.Smartlock.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260620215658_AddForeignKeyCascadeConstraints")]
    partial class AddForeignKeyCascadeConstraints
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.Access.Domain.Model.Aggregates.AccessGroup", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_access_groups");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("i_x_access_groups_organization_id");

                    b.ToTable("access_groups");
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.Access.Domain.Model.Aggregates.PersonAccess", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("AccessGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("access_group_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_person_accesses");

                    b.HasIndex("PersonId")
                        .IsUnique()
                        .HasDatabaseName("i_x_person_accesses_person_id");

                    b.ToTable("person_accesses");
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.Administration.Domain.Model.Aggregates.Membership", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint")
                        .HasColumnName("role_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("p_k_memberships");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("i_x_memberships_role_id");

                    b.ToTable("memberships");
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.Administration.Domain.Model.Aggregates.Role", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<bool>("Deletable")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("deletable");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_roles");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("i_x_roles_organization_id");

                    b.ToTable("roles");
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.Report.Domain.Model.Aggregates.ScheduleDay", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Day")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("day");

                    b.Property<long>("PersonId")
                        .HasColumnType("bigint")
                        .HasColumnName("person_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_schedule_days");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("i_x_schedule_days_person_id");

                    b.ToTable("schedule_days");
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.SpaceManagement.Domain.Model.Aggregates.Device", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("mode");

                    b.Property<long>("SiteId")
                        .HasColumnType("bigint")
                        .HasColumnName("site_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_devices");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("i_x_devices_site_id");

                    b.ToTable("devices");
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.SpaceManagement.Domain.Model.Aggregates.Organization", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_organizations");

                    b.ToTable("organizations");
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.SpaceManagement.Domain.Model.Aggregates.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<long?>("AccessGroupId")
                        .HasColumnType("bigint")
                        .HasColumnName("access_group_id");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_people");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("i_x_people_organization_id");

                    b.ToTable("people");
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.SpaceManagement.Domain.Model.Aggregates.Site", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)")
                        .HasColumnName("description");

                    b.Property<long>("OrganizationId")
                        .HasColumnType("bigint")
                        .HasColumnName("organization_id");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("p_k_sites");

                    b.HasIndex("OrganizationId")
                        .HasDatabaseName("i_x_sites_organization_id");

                    b.ToTable("sites");
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.Access.Domain.Model.Aggregates.AccessGroup", b =>
                {
                    b.HasOne("SmartIndustries.Smartlock.Platform.SpaceManagement.Domain.Model.Aggregates.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_access_groups__organization_organization_id");

                    b.OwnsOne("SmartIndustries.Smartlock.Platform.Shared.Domain.Model.ValueObjects.GenericName", "Name", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("name");

                            b1.HasKey("Id")
                                .HasName("p_k_access_groups");

                            b1.ToTable("access_groups");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_access_groups_access_groups_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.Access.Domain.Model.Aggregates.PersonAccess", b =>
                {
                    b.HasOne("SmartIndustries.Smartlock.Platform.SpaceManagement.Domain.Model.Aggregates.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_person_accesses__person_person_id");
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.Administration.Domain.Model.Aggregates.Membership", b =>
                {
                    b.HasOne("SmartIndustries.Smartlock.Platform.Administration.Domain.Model.Aggregates.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_memberships__role_role_id");
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.Administration.Domain.Model.Aggregates.Role", b =>
                {
                    b.HasOne("SmartIndustries.Smartlock.Platform.SpaceManagement.Domain.Model.Aggregates.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_roles__organization_organization_id");

                    b.OwnsOne("SmartIndustries.Smartlock.Platform.Shared.Domain.Model.ValueObjects.GenericName", "Name", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("name");

                            b1.HasKey("Id")
                                .HasName("p_k_roles");

                            b1.ToTable("roles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_roles_roles_id");
                        });

                    b.OwnsOne("SmartIndustries.Smartlock.Platform.Administration.Domain.Model.ValueObjects.RolePermissions", "Permissions", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<bool>("CanConnectDevices")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("can_connect_devices");

                            b1.Property<bool>("CanCreatePeople")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("can_create_people");

                            b1.Property<bool>("CanCreateSites")
                                .HasColumnType("tinyint(1)")
                                .HasColumnName("can_create_sites");

                            b1.HasKey("Id")
                                .HasName("p_k_roles");

                            b1.ToTable("roles");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_roles_roles_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();

                    b.Navigation("Permissions")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.OwnsOne("SmartIndustries.Smartlock.Platform.Shared.Domain.Model.ValueObjects.FullName", "Name", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("last_name");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.OwnsOne("SmartIndustries.Smartlock.Platform.Shared.Domain.Model.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("varchar(255)")
                                .HasColumnName("email");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("i_x_users_email");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.Report.Domain.Model.Aggregates.ScheduleDay", b =>
                {
                    b.HasOne("SmartIndustries.Smartlock.Platform.SpaceManagement.Domain.Model.Aggregates.Person", null)
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_schedule_days__person_person_id");

                    b.OwnsOne("SmartIndustries.Smartlock.Platform.Shared.Domain.Model.ValueObjects.TimeBlock", "TimeBlock", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<TimeOnly?>("End")
                                .HasColumnType("time(6)")
                                .HasColumnName("end");

                            b1.Property<TimeOnly?>("Start")
                                .HasColumnType("time(6)")
                                .HasColumnName("start");

                            b1.HasKey("Id")
                                .HasName("p_k_schedule_days");

                            b1.ToTable("schedule_days");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_schedule_days_schedule_days_id");
                        });

                    b.Navigation("TimeBlock")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.SpaceManagement.Domain.Model.Aggregates.Device", b =>
                {
                    b.HasOne("SmartIndustries.Smartlock.Platform.SpaceManagement.Domain.Model.Aggregates.Site", null)
                        .WithMany()
                        .HasForeignKey("SiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_devices__site_site_id");

                    b.OwnsOne("SmartIndustries.Smartlock.Platform.Shared.Domain.Model.ValueObjects.GenericName", "Name", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("name");

                            b1.HasKey("Id")
                                .HasName("p_k_devices");

                            b1.ToTable("devices");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_devices_devices_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.SpaceManagement.Domain.Model.Aggregates.Organization", b =>
                {
                    b.OwnsOne("SmartIndustries.Smartlock.Platform.Shared.Domain.Model.ValueObjects.GenericName", "Name", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("name");

                            b1.HasKey("Id")
                                .HasName("p_k_organizations");

                            b1.ToTable("organizations");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_organizations_organizations_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.SpaceManagement.Domain.Model.Aggregates.Person", b =>
                {
                    b.HasOne("SmartIndustries.Smartlock.Platform.SpaceManagement.Domain.Model.Aggregates.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_people_organizations_organization_id");

                    b.OwnsOne("SmartIndustries.Smartlock.Platform.Shared.Domain.Model.ValueObjects.IdentityDocument", "IdentityDocument", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("varchar(50)")
                                .HasColumnName("identity_document");

                            b1.HasKey("Id")
                                .HasName("p_k_people");

                            b1.ToTable("people");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_people__person_id");
                        });

                    b.OwnsOne("SmartIndustries.Smartlock.Platform.Shared.Domain.Model.ValueObjects.FullName", "Name", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("last_name");

                            b1.HasKey("Id")
                                .HasName("p_k_people");

                            b1.ToTable("people");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_people_people_id");
                        });

                    b.Navigation("IdentityDocument")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.SpaceManagement.Domain.Model.Aggregates.Site", b =>
                {
                    b.HasOne("SmartIndustries.Smartlock.Platform.SpaceManagement.Domain.Model.Aggregates.Organization", null)
                        .WithMany()
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("f_k_sites_organizations_organization_id");

                    b.OwnsOne("SmartIndustries.Smartlock.Platform.Shared.Domain.Model.ValueObjects.GenericName", "Name", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("varchar(100)")
                                .HasColumnName("name");

                            b1.HasKey("Id")
                                .HasName("p_k_sites");

                            b1.ToTable("sites");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_sites_sites_id");
                        });

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
