// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartIndustries.Smartlock.Platform.Shared.Infrastructure.Persistence.EntityFramerWorkCore.Configuration;

#nullable disable

namespace SmartIndustries.Smartlock.Platform.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.HasKey("Id")
                        .HasName("p_k_users");

                    b.ToTable("users");
                });

            modelBuilder.Entity("SmartIndustries.Smartlock.Platform.Iam.Domain.Model.Aggregates.User", b =>
                {
                    b.OwnsOne("SmartIndustries.Smartlock.Platform.Shared.Domain.Model.ValueObjects.Email", "Email", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("Value")
                                .IsRequired()
                                .HasColumnType("varchar(255)")
                                .HasColumnName("email");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.HasIndex("Value")
                                .IsUnique()
                                .HasDatabaseName("i_x_users_email");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.OwnsOne("SmartIndustries.Smartlock.Platform.Shared.Domain.Model.ValueObjects.FullName", "Name", b1 =>
                        {
                            b1.Property<long>("Id")
                                .HasColumnType("bigint")
                                .HasColumnName("id");

                            b1.Property<string>("FirstName")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("first_name");

                            b1.Property<string>("LastName")
                                .IsRequired()
                                .HasColumnType("longtext")
                                .HasColumnName("last_name");

                            b1.HasKey("Id")
                                .HasName("p_k_users");

                            b1.ToTable("users");

                            b1.WithOwner()
                                .HasForeignKey("Id")
                                .HasConstraintName("f_k_users_users_id");
                        });

                    b.Navigation("Email")
                        .IsRequired();

                    b.Navigation("Name")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
